export const accessibilityOptions = [
    { label: 'Blindness', value: 'Blindness' },
    { label: 'Vision Loss', value: 'Vision Loss' },
    { label: 'Color Blindness', value: 'Color Blindness' },
    { label: 'Dyslexia', value: 'Dyslexia' },
    { label: 'Deafness', value: 'Deafness' },
    { label: 'Hearing Loss', value: 'Hearing Loss' },
    { label: 'Speech Disorder (e.g., Apraxia, Stuttering)', value: 'Speech Disorder (e.g., Apraxia, Stuttering)' },
    { label: 'Cognitive Challenges (e.g., ADHD, Anxiety)', value: 'Cognitive Challenges (e.g., ADHD, Anxiety)' },
    { label: 'Memory Challenges (e.g., Dementia, Brain Fog)', value: 'Memory Challenges (e.g., Dementia, Brain Fog)' },
    { label: 'Executive Functioning Challenges (e.g., Difficulty with Planning or Task Switching)', value: 'Executive Functioning Challenges (e.g., Difficulty with Planning or Task Switching)' },
    { label: 'Motor Challenges (e.g., Arthritis, Tremors, Paralysis)', value: 'Motor Challenges (e.g., Arthritis, Tremors, Paralysis)' },
    { label: 'Photosensitivity', value: 'Photosensitivity' },
    { label: 'Epilepsy and/or Seizures', value: 'Epilepsy and/or Seizures' },
    { label: 'Spatial Sensitivity (e.g., VR/AR Motion Sickness, Vertigo)', value: 'Spatial Sensitivity (e.g., VR/AR Motion Sickness, Vertigo)' },
    { label: 'None', value: 'None' }
];

export const assistiveDeviceCategoryOptions = [
    { label: 'Screen Reader', value: 'Screen Reader', key: 'screen_reader' },
    { label: 'Screen Magnifier', value: 'Screen Magnifier', key: 'screen_magnifier' },
    { label: 'Visual Assistants', value: 'Visual Assistants', key: 'visual_assistants' },
    { label: 'Voice Recognition / Speech Generation', value: 'Voice Recognition / Speech Generation', key: 'voice_recognition' },
    { label: 'Hearing Aids / Tech', value: 'Hearing Aids / Tech', key: 'hearing_aids' },
    { label: 'Sing Language Virtual Interpreter', value: 'Sing Language Virtual Interpreter', key: 'sign_language' },
    { label: 'Input Devices', value: 'Input Devices', key: 'input_devices' },
    { label: 'None', value: 'none', key: 'none' }
];

export const assistiveDeviceOptions = {

    screen_reader: [
        { label: 'JAWS (Job Access With Speech)', value: 'JAWS' },
        { label: 'NVDA (NonVisual Desktop Access)', value: 'NVDA' },
        { label: 'Orca (Linux)', value: 'Orca' },
        { label: 'VoiceOver (Mac & iOS)', value: 'VoiceOver' },
        { label: 'Narrator (Windows OS)', value: 'Narrator' },
        { label: 'TalkBack (Android)', value: 'TalkBack' },
        { label: 'ChromeVox (Chrome OS)', value: 'ChromeVox' },
        { label: 'Edge Narrator (Microsoft Edge)', value: 'Edge Narrator' },
        { label: 'SAFA', value: 'SAFA' },
        { label: 'WebAnywhere', value: 'WebAnywhere' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    screen_magnifier: [
        { label: 'ZoomText', value: 'ZoomText' },
        { label: 'MAGic', value: 'MAGic' },
        { label: 'SuperNova Magnifier & Speech', value: 'SuperNova' },
        { label: 'Windows Magnifier', value: 'Windows Magnifier' },
        { label: 'macOS / iOS Zoom', value: 'macOS / iOS Zoom' },
        { label: 'Android Magnification', value: 'Android Magnification' },
        { label: 'Chrome Zoom (Built-in browser zoom)', value: 'Chrome Zoom' },
        { label: 'Edge Zoom (Built-in browser zoom)', value: 'Edge Zoom' },
        { label: 'Firefox Reader Mode & Zoom', value: 'Firefox Reader' },
        { label: 'Clover 10 & Ruby XL HD', value: 'Clover & Ruby' },
        { label: 'OrCam MyEye', value: 'OrCam MyEye' },
        { label: 'IrisVision Inspire & eSight', value: 'IrisVision' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    visual_assistants: [
        { label: 'Be My AI (Be My Eyes)', value: 'Be My AI' },
        { label: 'Seeing AI (Microsoft)', value: 'Seeing AI' },
        { label: 'Envision AI', value: 'Envision AI' },
        { label: 'Lookout (Google)', value: 'Lookout' },
        { label: 'VoiceVista', value: 'VoiceVista' },
        { label: 'Supersense', value: 'Supersense' },
        { label: 'Aira', value: 'Aira' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    voice_recognition: [
        { label: 'Dragon NaturallySpeaking', value: 'Dragon NaturallySpeaking' },
        { label: 'Voice Access (Google)', value: 'Voice Access' },
        { label: 'Apple Voice Control', value: 'Apple Voice Control' },
        { label: 'Windows Speech Recognition', value: 'Windows Speech Recognition' },
        { label: 'Siri Speech Commands (Apple)', value: 'Siri' },
        { label: 'Tobii Dynavox', value: 'Tobii Dynavox' },
        { label: 'PRC-Saltillo Accent Devices', value: 'PRC-Saltillo' },
        { label: 'Predictable', value: 'Predictable' },
        { label: 'Liberator Rugged 7', value: 'Liberator' },
        { label: 'BIGmack Communicator', value: 'BIGmack' },
        { label: 'Hawking Communicator', value: 'Hawking' },
        { label: 'Voiceitt', value: 'Voiceitt' },
        { label: 'Deepgram AI', value: 'Deepgram AI' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    hearing_aids: [
        { label: 'Phonak Audéo Paradise', value: 'Phonak Audéo Paradise' },
        { label: 'ReSound LiNX Quattro', value: 'ReSound LiNX Quattro' },
        { label: 'Oticon Opn S', value: 'Oticon Opn S' },
        { label: 'Starkey Livio AI', value: 'Starkey Livio AI' },
        { label: 'Widex Moment', value: 'Widex Moment' },
        { label: 'Signia Pure Charge&Go X', value: 'Signia Pure Charge&Go X' },
        { label: 'Cochlear Nucleus 7', value: 'Cochlear Nucleus 7' },
        { label: 'Eargo Neo HiFi', value: 'Eargo Neo HiFi' },
        { label: 'SoundWorld Solutions CS50+', value: 'SoundWorld Solutions CS50+' },
        { label: 'ClearCaptions', value: 'ClearCaptions' },
        { label: 'Otter.ai', value: 'Otter.ai' },
        { label: 'Google Live Transcribe', value: 'Google Live Transcribe' },
        { label: 'VibraLITE', value: 'VibraLITE' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    sign_language: [
        { label: 'SignAll', value: 'SignAll' },
        { label: 'AVA', value: 'AVA' },
        { label: 'Google Live Transcribe', value: 'Google Live Transcribe' },
        { label: 'HandTalk', value: 'HandTalk' },
        { label: 'Glide', value: 'Glide' },
        { label: 'ASL App', value: 'ASL App' },
        { label: 'Hands-up', value: 'Hands-up' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    input_devices: [
        { label: 'Standard Keyboard / Mouse', value: 'Standard Keyboard / Mouse' },
        { label: 'On-Screen Keyboard', value: 'On-Screen Keyboard' },
        { label: 'Alternative Keyboard', value: 'Alternative Keyboard' },
        { label: 'Voice Navigation and Input', value: 'Voice Navigation and Input' },
        { label: 'Gesture-based Navigation', value: 'Gesture-based Navigation' },
        { label: 'Eye Tracking Navigation', value: 'Eye Tracking Navigation' },
        { label: 'Gaze-Based Control System', value: 'Gaze-Based Control System' },
        { label: 'Electroencephalography (EEG) Headset', value: 'EEG Headset' },
        { label: 'Other', value: 'Other' },
        { label: 'None', value: 'None' },
    ],
    none: [
        { label: 'None', value: 'None' }
    ],
};

export const genderOptions = [
    { label: "She/Her", value: "She/Her" },
    { label: "He/Him", value: "He/Him" },
    { label: "They/Them", value: "They/Them" },
    { label: "Other", value: "Other" },
]

export const socialMediaOptions = [
    { label: "Facebook", value: "Facebook" },
    { label: "Instagram", value: "Instagram" },
    { label: "Twitter", value: "Twitter" },
    { label: "LinkedIn", value: "LinkedIn" },
    { label: "Telegram", value: "Telegram" },
    { label: "Bluesky", value: "Bluesky" },
    { label: "Other", value: "Other" }
]
